services:
  db:
    build:
      context: ./MySQL
      dockerfile: Dockerfile
    container_name: db
    restart: always
    volumes:
      - ./MySQL/data:/var/lib/mysql
    networks:
      - new_net
  nginx:
    build: ./nginx
    ports:
      - "8808:80"
    depends_on:
      - db
      - fastapi
      - adminer-balancer
    networks:
      - new_net
  adminer-balancer:
    image: adminer
    container_name: adminer-balancer
    restart: always
    networks:
      - new_net
  fastapi:
    build:
      context: ./FASTAPI
      dockerfile: Dockerfile
    container_name: fastapi
    restart: always
    networks:
      - new_net

networks:
  new_net:
    driver: bridge